/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppMenu: typeof import('./src/components/AppMenu.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElRow: typeof import('element-plus/es')['ElRow']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IMdiWindowClose: typeof import('~icons/mdi/window-close')['default']
    IMdiWindowMaximize: typeof import('~icons/mdi/window-maximize')['default']
    IMdiWindowMinimize: typeof import('~icons/mdi/window-minimize')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Titlebar: typeof import('./src/components/Titlebar.vue')['default']
  }
}
